Update deploy_vm_worker.yml

diff --git a/.github/workflows/deploy_vm_worker.yml b/.github/workflows/deploy_vm_worker.yml
--- a/.github/workflows/deploy_vm_worker.yml
+++ b/.github/workflows/deploy_vm_worker.yml
@@ -2,10 +2,10 @@ name: Deploy VMs
 on:
   workflow_dispatch:
     inputs:
-      vm_count:
-        description: "Number of VMs"
+      var_file:
+        description: "Variables file (within master directory)"
         required: true
-        default: "2"
+        default: "main.tf"
 jobs:
   deploy:
     runs-on: self-hosted
@@ -22,7 +22,7 @@ jobs:
       
       - name: View master folder contents
         run: |
-          ls -la ./vm-test/master || echo "Master folder not found in vm-test repository"
+          ls -la ./vm-test/worker || echo "Master folder not found in vm-test repository"
       
       - name: Install OpenTofu
         run: |
@@ -44,14 +44,14 @@ jobs:
           echo "vm-test directory files:"
           ls -la ./vm-test
           echo "vm-test/master directory files:"
-          ls -la ./vm-test/master || echo "Master folder not found"
+          ls -la ./vm-test/worker || echo "Master folder not found"
       
       - name: Initialize OpenTofu
-        working-directory: ./vm-test/master
+        working-directory: ./vm-test/worker
         run: tofu init
       
       - name: Apply OpenTofu Configuration
-        working-directory: ./vm-test/master
+        working-directory: ./vm-test/worker
         env:
           VM_COUNT: ${{ github.event.inputs.vm_count }}
         run: |
